### ISSUE TITLE
A strange warning in line 128

### ISSUE THREAD

**Issue by aocriup233** [Flundrahn/manim-fourier-project#2]
excepted value of type '(float, float) -> float'，but actually it is '(t: Any) -> ndarray'

**Comment by Flundrahn** [comment]
Looks like it has to do with calling `ParametricFunction` without the argument [use_vectorized = True](https://docs.manim.community/en/stable/reference/manim.mobject.graphing.functions.ParametricFunction.html?highlight=parametric%20function), but I couldn't get that to function.

I quick guess would be it is related to this change in [numpy ](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) and that Manim would need to pass the argument `dtype=object` somewhere.

As it doesn't break the code (using ManimCE 17.2) I won't touch it, if it does later I might have a go at it, or in case ManimCE team publishes an example on how to use the parameter use_vectorized = True.
